# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-04-11 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0023_auto_20230510_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='language',
            field=models.CharField(choices=[('', '-------'), ('en', 'English'), ('de', 'German'), ('eu', 'Basque'), ('tr', 'Turkish'), ('es', 'Spanish'), ('fr', 'French'), ('it', 'Italian'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('ja', 'Japanese'), ('pt', 'Portuguese'), ('nl', 'Dutch'), ('pl', 'Polish'), ('ar', 'Arabic'), ('uk', 'Ukrainian')], default='', max_length=8),
        ),
    ]
