# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-05-14 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0037_auto_20260514_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='language',
            field=models.CharField(choices=[
                ('', '-------'),
                ('en', 'English'),
                ('de', 'German'),
                ('eu', 'Basque'),
                ('tr', 'Turkish'),
                ('es', 'Spanish'),
                ('fr', 'French'),
                ('it', 'Italian'),
                ('hu', 'Hungarian'),
                ('id', 'Indonesian'),
                ('ja', 'Japanese'),
                ('pt', 'Portuguese'),
                ('nl', 'Dutch'),
                ('pl', 'Polish'),
                ('ar', 'Arabic'),
                ('uk', 'Ukrainian'),
                ('dsb', 'Lower Sorbian'),
                ('sv', 'Swedish'),
                ('ru', 'Russian'),
                ('hi', 'Hindi'),
                ('fa', 'Persian'),
                ('zh', 'Chinese'),
                ('vi', 'Vietnamese'),
                ('ce', 'Chechen'),
                ('sr', 'Serbian'),
                ('no', 'Norwegian'),
                ('fi', 'Finnish'),
                ('cs', 'Czech'),
                ('ro', 'Romanian'),
                ('sh', 'Serbo-Croatian'),
                ('ms', 'Malay'),
                ('th', 'Thai'),
                ('he', 'Hebrew'),
                ('ml', 'Malayalam'),
                ('tl', 'Tagalog'),
                ('ur', 'Urdu'),
                ('ne', 'Nepali'),
                ('sq', 'Albanian'),
                ('als', 'Alemannisch'),
                ('be', 'Belarusian'),
                ('bn', 'Bengali'),
                ('eo', 'Esperanto'),
                ('ka', 'Georgian'),
                ('ia', 'Interlingua'),
                ('vec', 'Venetian'),
                ('uz', 'Uzbek'),
                ('da', 'Danish'),
                ('bg', 'Bulgarian'),
                ('cy', 'Welsh'),
                ('simple', 'Simple English'),
                ('el', 'Greek'),
                ('sk', 'Slovak'),
                ('et', 'Estonian'),
                ('kk', 'Kazakh'),
                ('hr', 'Croatian'),
                ('gl', 'Galician'),
                ('lt', 'Lithuanian'),
            ], default='', max_length=8),
        ),
    ]
